---
- name: deploy Zabbix Agent/Proxy/Server
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:


    - name: check if Zabbix Agent2 was already configured
      find:  
        paths: /etc/zabbix/
        patterns: zabbix_agent2.conf
      register: zabbixPresent

    - name: Check if config contains correct address string
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^ServerActive=loki'
        line: ""
      check_mode: yes
      register: config
      when: zabbixPresent.matched > 0 and zabbixPresent.matched is defined

    - name: End the play for hosts are already setup
      meta: end_host
      when:
        - zabbixPresent.matched > 0 and zabbixPresent.matched is defined and config.changed == true

    - name: Download Zabbix Repo for debian systems
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-2%2Bubuntu22.04_all.deb
        dest: /home/andrei/zabbix-release_622.deb
        mode: '0440'
      when: ansible_distribution_version == "22.04"

        
    - name: Install a .deb package from the internet
      apt:
        deb: /home/andrei/zabbix-release_622.deb
      when: ansible_distribution_version == "22.04"
      
    - name: enable Zabbix Repo on RHEL 9 or Fedora 36
      shell: rpm -Uvh https://repo.zabbix.com/zabbix/6.2/rhel/9/x86_64/zabbix-release-6.2-3.el9.noarch.rpm & yum clean all
      register: repoState
      failed_when:  
        - '"already installed" not in repoState.stderr'
        - '"warning" not in repoState.stderr'
        - '"listed more than once" not in repoState.stderr'
        - repoState.stderr != ""        
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9" || ansible_distribution_major_version == "36"
      ignore_errors: yes
    
    - name: Update packages
      dnf:
        name: "*"
        state: latest
      when: ansible_pkg_mgr ==  "dnf"
      
    - name: Update packages
      apt:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == "apt"


    - name: Install Zabbix Agent
      yum:
        name: 
          - zabbix-agent2
        state: latest

    - name: Copy the Zabbix script to target
      copy: 
        src: zabbix_agent2.conf 
        dest: /etc/zabbix/zabbix_agent2.conf 
        mode: '0644'
        backup: yes

    - name: Restart Rabbix Agent
      service:
        name: zabbix-agent2
        enabled: yes
        state: restarted

    - name: Enable Zabbix Agent
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
      - zabbix-agent2
