---
- name: Upgrade all packages
  hosts: all
  gather_facts: no
  tasks:
    
    - name: Gathering Facts
      setup:
      register: setup
      changed_when: "{{setup.msg}}" != ""
    
    - name: Update all apt packages to their latest version
      apt:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == "apt"
    
    - name: Update all dnf packages to their latest version
      dnf:
        name: "*"
        state: latest
      when: ansible_pkg_mgr ==  "dnf"
